version: "3.9"

networks:
  skbackend_network:
    name: skbackend_network

services:
  skbackend_db:
    container_name: skbackend_pg_container
    image: postgres:13-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - skbackend_pg_volume:/var/lib/postgresql/data/
    networks:
      - skbackend_network
    restart: always

  skbackend_server:
    container_name: skbackend_go_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - skbackend_network
    depends_on:
      - skbackend_db
    volumes:
      - .:/app:rw,cached
    restart: always

volumes:
  skbackend_pg_volume: