version: "3.9"

networks:
  meals-network:
    name: meals-network

services:
  meals-pg:
    container_name: meals-pg
    image: postgres:13-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - meals-pg-volume:/var/lib/postgresql/data/
    networks:
      - meals-network
    restart: always

  meals-go:
    container_name: meals-go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - meals-network
    depends_on:
      - meals-pg
      - meals-redis
    volumes:
      - .:/app:rw,delegated
    restart: always

  meals-redis:
    container_name: meals-redis
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - meals-redis-volume:/data
    networks:
      - meals-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  meals-pg-volume:
  meals-redis-volume: